tienthienhd/tc-edoc

src-ui/messages.xlf
src-ui/src/locale/messages.vi_VN.xlf
src/documents/templates/account/login.html
src/locale/vi_VN/LC_MESSAGES/django.po

fix: revise title to TC GROUP

---

script_run.sh

fix: mount folder media

---

src-ui/src/locale/messages.vi_VN.xlf

fix: translate vie

---

src/locale/en_US/LC_MESSAGES/django.po

fix: translate vi

---

src/documents/templates/index.html

fix: update title

---

requirements.txt

fix: add PyPDF2

---

.env

fix: update env

---

Pipfile.lock

fix: pjpfile.clock

---

Pipfile
Pipfile.lock

fix: pipfile update

---

Pipfile
Pipfile.lock
src-ui/src/locale/messages.vi_VN.xlf

fix: pypdf2

---

src/paperless_ocr_custom/parsers.py

fix: call ocr api with retries

---

src/paperless_ocr_custom/parsers.py

fix : fix size image

---

src/documents/serialisers.py
src/documents/views.py

update bulkedit vs input parent_warehouse not null

---

src/paperless_ocr_custom/parsers.py

fix: Update page size

---

src/documents/views.py

fix: warehouse

---

src/documents/views.py

fix: create warehouse

---

src/documents/serialisers.py
src/documents/views.py

fix:change-status-warehouse

---

src-ui/src/app/data/workflow-action.ts
src-ui/src/app/data/workflow-trigger.ts
src/documents/serialisers.py

fix:warehouse-in-workflow

---

src/documents/consumer.py
src/documents/signals/handlers.py

fix:remove-warehouses

---

src/documents/serialisers.py
src/documents/views.py

fix:count-warehouse

---

src/documents/parsers.py

fix: ocr key

---

src/documents/views.py

fix:filter-warehouse

---

src/documents/serialisers.py
src/documents/views.py

fix:filter-folders-documents

---

src/documents/views.py

fix:get-folder

---

src/documents/views.py

fix:get-folders-documents

---

src/documents/views.py

fix:count-folder/

---

src/documents/serialisers.py
src/documents/views.py

fix:insert-folder

---

src/documents/serialisers.py

fix:change_name

---

src/documents/filters.py
src/documents/serialisers.py
src/documents/views.py

fix:filesize_folder

---

src/documents/serialisers.py

fix:validate-update

---

src/documents/serialisers.py

fix:validate-update-data

---

src/documents/filters.py
src/documents/serialisers.py
src/documents/views.py

fixbug:update-folder

---

src/documents/filters.py
src/documents/serialisers.py
src/documents/views.py

fix:delete-document

---

src-ui/src/app/components/dashboard/widgets/upload-file-widget/upload-file-widget.component.ts
src-ui/src/app/components/manage/custom-folder-list/custom-folder-list.component.html
src-ui/src/app/components/manage/custom-folder-list/custom-folder-list.component.scss
src-ui/src/app/services/upload-documents.service.ts
src/documents/consumer.py

add upload file from folder-fe

---

src-ui/src/app/app-routing.module.ts
src-ui/src/app/components/common/custom-fields-dropdown/custom-fields-dropdown.component.ts
src-ui/src/app/components/manage/box-fields/box-fields.component.ts
src-ui/src/app/components/manage/custom-shelf/custom-shelf.component.ts
src-ui/src/app/services/permissions.service.ts
src-ui/src/locale/messages.vi_VN.xlf

fix bug warehouse fe and custom field from documentdetail

---

src/documents/consumer.py
src/paperless_ocr_custom/parsers.py

fix ocr parsing 0

---

src-ui/src/app/components/common/edit-dialog/edit-customshelf/edit-customshelf.component.ts
src/paperless_ocr_custom/parsers.py

count page number

---

src/documents/bulk_edit.py

fix bug bulk edit (delete) document

---

src/documents/consumer.py
src/paperless_ocr_custom/parsers.py

edit fields

---

src/paperless_ocr_custom/parsers.py

fix read pdf

---

src/documents/bulk_edit.py
src/documents/consumer.py
src/documents/serialisers.py
src/documents/views.py

delete dossier, delete document, delete folder

---

src/documents/serialisers.py

fix error parent_warehouse.id 'NoneType' object has no attribute 'id'

---

src/documents/serialisers.py

fix return warehouse, shelf

---

src/documents/consumer.py
src/paperless_ocr_custom/parsers.py
src/paperless_ocr_custom/signals.py

define type another
